# Generated by Django 5.2.7 on 2026-03-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0003_creditusage_token_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
