# Generated by Django 5.2.7 on 2026-03-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0004_delete_job'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditusage',
            name='creatorscri_user_id_19c6f7_idx',
        ),
        migrations.RemoveField(
            model_name='creditusage',
            name='action_type',
        ),
    ]
