# Generated by Django 5.2.7 on 2026-03-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0005_remove_creditusage_creatorscri_user_id_19c6f7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_industr_f9c8a6_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_post_time',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='youtube_url',
        ),
    ]
