# Generated by Django 5.2.7 on 2026-03-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0006_remove_client_clients_industr_f9c8a6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook (Meta)'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X')], help_text='Social media platform', max_length=20)),
                ('account_name', models.CharField(help_text='Display name or handle of the account', max_length=255)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client this social account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='creatorscribe_api.client')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
                'indexes': [models.Index(fields=['client', 'platform'], name='social_acco_client__e34950_idx')],
                'unique_together': {('client', 'platform')},
            },
        ),
    ]
