# Generated by Django 5.2.7 on 2026-03-17 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0008_rename_user_client_owner_add_clientmember'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_owner_i_c6469b_idx',
            old_name='clients_owner_client_name_idx',
        ),
        migrations.RenameIndex(
            model_name='clientmember',
            new_name='client_memb_client__b10eff_idx',
            old_name='client_members_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='clientmember',
            new_name='client_memb_user_id_13f669_idx',
            old_name='client_members_user_status_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(help_text='User who created and owns this client', on_delete=django.db.models.deletion.CASCADE, related_name='owned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Whether the invite has been accepted', max_length=20),
        ),
    ]
