# Generated by Django 5.2.7 on 2026-03-19 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0010_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_sessions', to='creatorscribe_api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caption_sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['client', '-updated_at'], name='caption_ses_client__0a98b6_idx'), models.Index(fields=['user', '-updated_at'], name='caption_ses_user_id_d36eef_idx')],
            },
        ),
    ]
