# Generated by Django 5.2.7 on 2026-03-19 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0011_captionsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('none', 'None')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Audio'), ('transcribing', 'Transcribing'), ('captioning', 'Generating Captions'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_jobs', to='creatorscribe_api.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='creatorscribe_api.captionsession')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caption_jobs', to='creatorscribe_api.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caption_jobs',
                'ordering': ['turn_index'],
            },
        ),
        migrations.CreateModel(
            name='AudioOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/')),
                ('duration', models.FloatField(null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='creatorscribe_api.captionjob')),
            ],
            options={
                'db_table': 'caption_audio_outputs',
            },
        ),
        migrations.CreateModel(
            name='CaptionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caption', to='creatorscribe_api.captionjob')),
            ],
            options={
                'db_table': 'caption_outputs',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='creatorscribe_api.captionjob')),
            ],
            options={
                'db_table': 'caption_transcription_outputs',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('start_second', models.FloatField()),
                ('end_second', models.FloatField()),
                ('index', models.PositiveIntegerField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='creatorscribe_api.transcriptionoutput')),
            ],
            options={
                'db_table': 'caption_transcription_segments',
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='captionjob',
            index=models.Index(fields=['client', '-created_at'], name='caption_job_client__e5387a_idx'),
        ),
        migrations.AddIndex(
            model_name='captionjob',
            index=models.Index(fields=['session', 'turn_index'], name='caption_job_session_ed5071_idx'),
        ),
    ]
