# Generated by Django 5.2.7 on 2026-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorscribe_api', '0012_captionjob_audiooutput_captionoutput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionsession',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
